### ISSUE TITLE
Allow cloud "restore" without node configuration

### ISSUE THREAD

**Issue by Allan-N** [AllStarLink/asl3-menu#40]
At present, one must configure at least the "node" and "node password" in order to restore an ASL backup from the cloud.  If either is missing we should prompt for the needed information so that one could start with a fresh/clean install and restore from a backup.

**Comment by Allan-N** [comment]
Note: when restoring the "template" configuration we should generate a new/random manager secret (or, if available, restore the one saved in allmon3.ini)

**Comment by tsawyer** [comment]
If this issue is related to #49,  is the suggestion not allow a restore from /usr/share/asterisk/conf/asl3 if there is a local backup?

**Comment by Allan-N** [comment]
The two issues are related, but different.  One would allow you to restore a previously saved configuration while the other would allow you to start over.

And, yes, we could even combine the two with the "template" configuration being one of the backups you could choose to restore. Using the backup and restore menu might be an alternative to adding another item to asl-menu.
