### ISSUE TITLE
Menu improvements

### ISSUE THREAD

**Issue by Allan-N** [AllStarLink/asl3-menu#46]
There have been a handful of requests for menu "improvements".

The requests we will be focusing on now include :
- Nodes w/duplex==0 "Half duplex with no telemetry (link)"
Nodes with no telemetry can actually be configured for "Full duplex" (controlled by "linktolink").  We should have the menu allow no telemetry in half or full duplex configurations and update "linktolink" accordingly.

- Nodes w/duplex==1 "Half duplex with telemetry (hotspot)"
The default telemetry events are not well suited for hotspots.  The request is to note  when duplex==1 has been selected and switch from using the default telemetry events [wait-times] to using the half-duplex telemetry events  [wait-times_hd].

- New nodes
Here, the request is to simplify the configuration of "new" nodes.  We will now ask what type of node is being created (e.g. hotspot, repeater, voter) and set the defaults for the new node accordingly.

**Comment by tsawyer** [comment]
In addition to duplex 1 settings, a `hangtime = ` should be added to the users node settings with a value of 300 or 500 milliseconds.
