### ISSUE TITLE
Hotspot should not have linktolink

### ISSUE THREAD

**Issue by tsawyer** [AllStarLink/asl3-menu#52]
Menu selection `Hotspot (half duplex) with no courtesy tones` should not add `linktolink`. That setting is for hardwired **links** to controller ports. 

```
[54321](node-main)
statpost_url = http://stats.allstarlink.org/uhandler
idrecording = |iW6XYZ
duplex = 0
hangtime = 100
linktolink =
rxchannel = Radio/54321
```

**Comment by Allan-N** [comment]
This was a bug in the "menu improvement" changes for issue #46.  A fix has just been added to that branch/PR.
