### ISSUE TITLE
USBRadio (and SimpleUSB) not assigning "devstr" when multiple interfaces are present.

### ISSUE THREAD

**Issue by Allan-N** [AllStarLink/asl3-menu#54]
From Community [#21570](https://community.allstarlink.org/t/asl3-add-second-node/21570) :

> From the ASL-MENU, NODE SETUP, I add a node and enter the information. When I go to ’ interface tune CLI ', it must restart asterisk. Then when I go back to ’ interface tune CLI ', the new node is not there, it cannot be selected? I see that ’ rpt.conf ’ seems to have the node added, but ’usbradio.conf’ does not.

I have also reproduced this issue on a Dell/Wyse 3040 with 2 CM108 dongles.  With 2 nodes configured and "simpleusb.conf" having "devstr = " for one (or both) of the nodes then the 2nd node will not be assigned a device string.

**Comment by KB4MDD** [comment]
Discussions about this issue are ongoing with the development team.  I believe this is the result of idrecording being set to a null string.  

app_rpt presently requires an idrecording and if not present stops the processing thread.

**Comment by Allan-N** [comment]
We were thinking that not all nodes needed a callsign ID (e.g. radio-less).  It turns out that, for now, the lack of a callsign ID was keeping app_rpt from running the node.

For now, we need to add back the requirement that each node has a callsign ID.
