### ISSUE TITLE
Changing IAX port number inappropriately string replaces other node entries in rpt.conf

### ISSUE THREAD

**Issue by jxmx** [AllStarLink/asl3-menu#66]
If I use the feature to change the IAX port number, the script overwrites the port of any hardcoded connection in `rpt.conf`. Example:

```
460181 = radio@127.0.0.1:4568/460181,NONE
48496 = radio@172.17.16.54:4568/48496,NONE
2116 = radio@172.17.16.66:4568/2116,NONE
```

These previously were, respectively 4567, 4569, and 4566. Only node 460181 is on this server.

**Comment by Allan-N** [comment]
Who added all of those non-local nodes that each use a different port # ??? :-)

**Comment by Allan-N** [comment]
Q? is it enough to check/update nodes with a 127.0.0.1 IP?  or should I check/update local nodes with a [12345] stanza?  or do I need to check for any IP address for the local host?

**Comment by jxmx** [comment]
I would think that changing only the 127.0.0.1(s) would be the 99% use case.
